---
name: Release

"on":
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: false
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 21 (for building)
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JARs
        run: |
          chmod +x ./gradlew
          ./gradlew clean build fatJar
          
      - name: List built artifacts
        run: |
          echo "Built artifacts:"
          find lib/build/libs -name "*.jar" -ls
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lib/build/libs/jackson-databind-jsonc-*.jar
          generate_release_notes: true

      - name: Verify Sonatype Configuration
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          echo "Verifying Sonatype configuration..."
          echo "OSSRH_USERNAME is set: ${{ secrets.OSSRH_USERNAME != '' }}"
          echo "OSSRH_PASSWORD is set: ${{ secrets.OSSRH_PASSWORD != '' }}"
          ./gradlew tasks --group=publishing

      - name: Test Nexus connectivity (optional)
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          echo "Testing Nexus connectivity..."
          # Try to retrieve staging profile (this will fail in some environments but helps debug)
          ./gradlew retrieveSonatypeStagingProfile --continue || echo "Staging profile retrieval failed (expected in some environments)"

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "Publishing to Maven Central..."
          echo "Step 1: Build and publish to Sonatype staging..."
          ./gradlew publishToSonatype --info --stacktrace --no-daemon
          echo "Step 2: Close and release staging repository..."
          ./gradlew closeAndReleaseSonatypeStagingRepository --info --stacktrace --no-daemon
