name: Release

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build fatJar

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release notes for ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload JAR file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lib/build/libs/lib-1.0.0.jar
          asset_name: lib-1.0.0.jar
          asset_content_type: application/java-archive
