---
name: Release

"on":
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: false
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 21 (for building)
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JARs
        run: |
          chmod +x ./gradlew
          ./gradlew clean build fatJar
          
      - name: List built artifacts
        run: |
          echo "Built artifacts:"
          find lib/build/libs -name "*.jar" -ls
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lib/build/libs/jackson-databind-jsonc-*.jar
          generate_release_notes: true

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "Publishing to Maven Central..."
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
